"""empty message

Revision ID: 0dbf7a4b7a10
Revises: 755a46b318c1
Create Date: 2020-06-17 08:34:20.007129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dbf7a4b7a10'
down_revision = '755a46b318c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('classCode', sa.String(length=6), nullable=True))
    op.create_unique_constraint(None, 'group', ['classCode'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group', type_='unique')
    op.drop_column('group', 'classCode')
    # ### end Alembic commands ###
