"""question answers table

Revision ID: 48ab5b87d2aa
Revises: bbae3d7e3b5e
Create Date: 2020-05-09 17:35:27.450342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48ab5b87d2aa'
down_revision = 'bbae3d7e3b5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('optId', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_answer'), 'answer', ['answer'], unique=True)
    op.create_index(op.f('ix_answer_optId'), 'answer', ['optId'], unique=True)
    op.create_table('option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qnId', sa.Integer(), nullable=True),
    sa.Column('option', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_option_option'), 'option', ['option'], unique=True)
    op.create_index(op.f('ix_option_qnId'), 'option', ['qnId'], unique=True)
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_question'), 'question', ['question'], unique=True)
    op.create_index(op.f('ix_user_urole'), 'user', ['urole'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_urole'), table_name='user')
    op.drop_index(op.f('ix_question_question'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_option_qnId'), table_name='option')
    op.drop_index(op.f('ix_option_option'), table_name='option')
    op.drop_table('option')
    op.drop_index(op.f('ix_answer_optId'), table_name='answer')
    op.drop_index(op.f('ix_answer_answer'), table_name='answer')
    op.drop_table('answer')
    # ### end Alembic commands ###
