"""empty message

Revision ID: 4a9ec06a650c
Revises: 48ab5b87d2aa
Create Date: 2020-05-09 17:47:11.898990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a9ec06a650c'
down_revision = '48ab5b87d2aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_option_qnId', table_name='option')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_option_qnId', 'option', ['qnId'], unique=1)
    # ### end Alembic commands ###
