"""drop username

Revision ID: 92035e88cba4
Revises: cd63d7301e53
Create Date: 2020-05-09 23:10:33.481426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92035e88cba4'
down_revision = 'cd63d7301e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
