@startuml
package Controller {
Class Questions
Class Email
Class Forum
Interface Routes <<Interface>>
}

package Model{
}

package View{
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Routes

Routes --> Questions
Routes --> Email
Routes --> Forum
Questions --> Model
Email --> Model
Forum --> Model
Routes --> View
@enduml