@startuml
' avoid problems with angled crows feet
skinparam linetype ortho

entity User {
*id
--
firstName
lastName
email
password_hash
urole
confirmed
confirmed_on
proficiency
}

entity Response {
*id
--
userID
optId
qnId
}

entity Question {
*id
--
question
discrimination
difficulty
guessing
upper
}

entity Option {
*id
--
qnId
option
}

entity Answer {
*id
--
optId
qnId
}

entity Thread {
*id
--
groupID
timestamp
}

entity Post {
*id
--
userID
threadID
timestamp
title
content
}

entity Group {
*id
--
name
}

entity UserGroup {
*id
--
groupID
userID
}

entity Proficiency {
*id
--
userID
datetime
theta
}

User ||--|{ Response

Response }|--|| Option
Response }|--|| Question
Option }|--|| Question
Answer ||--|| Question
Option ||--|| Answer


User ||--|{ UserGroup
Group ||--|{ UserGroup
Thread }|--|| Group
Post }|--|| Thread
Post }|--|| User
User ||--|{ Proficiency

@enduml
