@startuml
' avoid problems with angled crows feet
skinparam linetype ortho

entity User {
*id
--
firstName
lastName
email
password_hash
urole
confirmed
confirmed_on
}

entity Question {
*id
--
question
score
}

entity Option {
*id
--
qnId
option
}

entity Answer {
*id
--
optId
userID
}

entity Post {
*id
--
title
content
}

entity Class {
*id
--
name
}

entity UserClass {
*id
--
classID
userID
}

User ||--|{ Answer

Answer ||--|{ Option
Option }|--|| Question

User ||--|{ UserClass
Class ||--|{ UserClass
UserClass ||--|{ Post

@enduml
