@startuml
' avoid problems with angled crows feet
skinparam linetype ortho

entity User {
*id
--
firstName
lastName
email
password_hash
urole
confirmed
confirmed_on
proficiency
}

entity Response {
*id
--
userID
optId
qnId
}

entity Question {
*id
--
question
score
discrimination
difficulty
guessing
upper
}

entity Option {
*id
--
qnId
option
}

entity Answer {
*id
--
optId
qnId
}

entity Post {
*id
--
title
content
}

entity Class {
*id
--
name
}

entity UserClass {
*id
--
classID
userID
}

User ||--|{ Response

Response }|--|| Option
Response }|--|| Question
Option }|--|| Question
Answer ||--|| Question
Option ||--|| Answer


User ||--|{ UserClass
Class ||--|{ UserClass
UserClass ||--|{ Post

@enduml
